//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsSender.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSCollection
    {
        public int SMSId { get; set; }
        public string PhoneNumber { get; set; }
        public string MessageContent { get; set; }
        public int Priority { get; set; }
        public bool IsSent { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> RecievedDateStamp { get; set; }
        public Nullable<System.DateTime> SentDateStamp { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
